version: '3.9'
services:
  postgres:
    image: postgres
    restart: always
    command: postgres -c 'max_connections=2000'
    environment:
      POSTGRES_PASSWORD: aioshima
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      - BITNAMI_DEBUG=true
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=INTERNAL
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,INTERNAL://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:SASL_PLAINTEXT,INTERNAL:SASL_PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://103.234.150.144:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@:9093
      #      - KAFKA_CERTIFICATE_PASSWORD=KhangLam165
      - KAFKA_INTER_BROKER_USER=${CLIENT_USER}
      - KAFKA_INTER_BROKER_PASSWORD=${CLIENT_PASSWORD}
      - KAFKA_CLIENT_USERS=${CLIENT_USER}
      - KAFKA_CLIENT_PASSWORDS=${CLIENT_PASSWORD}
      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=PLAIN
      - KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL=PLAIN
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
    volumes:
      - ./kafka:/bitnami/kafka
volumes:
  pgdata:
